Changed paths: M       Progs/CAT_DumpCurvL4FS
Always write ??.central in CAT_DumpCurvL4FS.


git-svn-id: svn://141.35.69.214/CAT@253 85a05d3d-4204-4b9d-9be8-300d97d0f21f

diff --git a/Progs/CAT_DumpCurvL4FS b/Progs/CAT_DumpCurvL4FS
--- a/Progs/CAT_DumpCurvL4FS
+++ b/Progs/CAT_DumpCurvL4FS
@@ -22,7 +22,7 @@ fwhm=0
 
 main ()
 {
-	check_tools
+  check_tools
   parse_args ${1+"$@"}
   DumpCurv
 
@@ -62,37 +62,33 @@ DumpCurv ()
 
   if [ -n "$ARGV_list" ]
   then
-		for subject in $ARGV_list
-		do
-		  outputname=${subject}/surf/
-		  if [ ! -d "$outputname" ]; then
-	  		echo Directory $outputname not found.
-	  		exit 1
-	  	fi
-    	echo calculating ${subject} 
-    	tmp_name=/tmp/$$_avg
-    	for hemi in lh rh; do
-    		for name in ${outputname}${hemi}.white ${outputname}${hemi}.pial; do
-				  if [ ! -f "$name" ]; then
-			  		echo File $name not found.
-	  				exit 1
-	  			fi
-	  		done
-	    	CAT_AverageSurfaces -avg $tmp_name ${outputname}${hemi}.white ${outputname}${hemi}.pial >/dev/null 2>&1
-			  if [ ! -f "$tmp_name" ]; then
-		  		echo File $tmp_name not found. Error using CAT_AverageSurfaces.
-  				exit 1
-  			fi
-  	  	CAT_DumpCurv $tmp_name ${outputname}${hemi}.${str}_central $method $fwhm $use_absolute
-  	  	rm $tmp_name
-  		done
-  	done
+    for subject in $ARGV_list
+    do
+      outputname=${subject}/surf/
+      if [ ! -d "$outputname" ]; then
+        echo Directory $outputname not found.
+        exit 1
+      fi
+      echo calculating ${subject} 
+      for hemi in lh rh; do
+        for name in ${outputname}${hemi}.white ${outputname}${hemi}.pial; do
+          if [ ! -f "$name" ]; then
+            echo File $name not found.
+            exit 1
+          fi
+        done
+        if [ ! -f ${outputname}${hemi}.central ]; then
+          CAT_AverageSurfaces -avg ${outputname}${hemi}.central ${outputname}${hemi}.white ${outputname}${hemi}.pial >/dev/null 2>&1
+        fi
+        CAT_DumpCurv ${outputname}${hemi}.central ${outputname}${hemi}.${str}_central $method $fwhm $use_absolute
+      done
+    done
   else
-		echo "No arguments given."
-		echo
-		usage
-		echo "Use the --help option for more information."
-		exit 1
+    echo "No arguments given."
+    echo
+    usage
+    echo "Use the --help option for more information."
+    exit 1
   fi
 
 }
@@ -109,43 +105,43 @@ parse_args ()
 
   while [ $# -gt 0 ]
   do
-	optname="`echo $1 | sed 's,=.*,,'`"
-	optarg="`echo $1 | sed 's,^[^=]*=,,'`"
-	case "$1" in
-		--a* | -a*)
-			use_absolute=1
-			;;
-		--f* | -f*)
-			optarg=`echo $optarg | sed 's,[^0-9],,g'`
-			exit_if_empty "$optname" "$optarg"
-			fwhm=$optarg
-			;;
-		--mc | -mc)
-			method=0
-			;;
-		--g* | -g*)
-			method=1
-			;;
-		--c* | -c*)
-			method=2
-			;;
-		--s* | -s*)
-			method=3
-			;;
-		--mc0 | -mc0)
-			method=4
-			;;
-		-h | --help | -v | --version | -V)
-			help
-			exit 1
-			;;
-		-*)
-			echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
-			;;
-		*)
-			ARGV_list="$ARGV_list $1"
-			;;
-	esac
+  optname="`echo $1 | sed 's,=.*,,'`"
+  optarg="`echo $1 | sed 's,^[^=]*=,,'`"
+  case "$1" in
+    --a* | -a*)
+      use_absolute=1
+      ;;
+    --f* | -f*)
+      optarg=`echo $optarg | sed 's,[^0-9],,g'`
+      exit_if_empty "$optname" "$optarg"
+      fwhm=$optarg
+      ;;
+    --mc | -mc)
+      method=0
+      ;;
+    --g* | -g*)
+      method=1
+      ;;
+    --c* | -c*)
+      method=2
+      ;;
+    --s* | -s*)
+      method=3
+      ;;
+    --mc0 | -mc0)
+      method=4
+      ;;
+    -h | --help | -v | --version | -V)
+      help
+      exit 1
+      ;;
+    -*)
+      echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
+      ;;
+    *)
+      ARGV_list="$ARGV_list $1"
+      ;;
+  esac
     shift
   done
 
@@ -166,8 +162,8 @@ exit_if_empty ()
 
   if [ -z "$val" ]
   then
-	echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
-	exit 1
+  echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
+  exit 1
   fi
 }
 
@@ -177,12 +173,12 @@ exit_if_empty ()
 
 check_tools ()
 {
-	for name in CAT_DumpCurv CAT_AverageSurfaces; do
-	  found=`which ${name}`
-  	if [ ! -n "$found" ];then
-    	echo $name not found.
-    	exit 1
-  	fi
+  for name in CAT_DumpCurv CAT_AverageSurfaces; do
+    found=`which ${name}`
+    if [ ! -n "$found" ];then
+      echo $name not found.
+      exit 1
+    fi
   done
 }
 
@@ -194,7 +190,7 @@ usage ()
 cat <<__EOM__
 USAGE: CAT_DumpCurvL4FS subject [subject2 .. subjectN] [-mc|-mc0|-gc|-cv|-si] [-a]
         [-f=fwhm_in_mm]
-		
+    
 __EOM__
 }
 
@@ -217,14 +213,14 @@ USAGE:
         [-f=fwhm_in_mm]
     
 OPTIONS:
-	subject    - one or more subject directories
-	-f         - diffusion heat kernel smoothing defined in fwhm in mm
-	-a         - calculate absolute values of parameters [default]
-	-mc        - calculate mean curvature averaged over 3mm [default]                
-	-mc0       - calculate mean curvature                
-	-gc        - calculate gaussian curvature                
-	-cv        - calculate curvedness                
-	-si        - calculate shape index                
+  subject    - one or more subject directories
+  -f         - diffusion heat kernel smoothing defined in fwhm in mm
+  -a         - calculate absolute values of parameters [default]
+  -mc        - calculate mean curvature averaged over 3mm [default]                
+  -mc0       - calculate mean curvature                
+  -gc        - calculate gaussian curvature                
+  -cv        - calculate curvedness                
+  -si        - calculate shape index                
     
 EXAMPLE:
     CAT_DumpCurvL4FS ${SUBJECTS_DIR}/[a-d]* -mc -a
