Changed paths: M       depcomp M       INSTALL M       mkinstalldirs M       Progs/CAT_DumpCurvL4FS_ui M       Progs/CAT_DumpCurv_ui M       Progs/CAT_ResampleFS_ui M       Progs/CAT_FractalDimensionFS_ui M       Progs/CAT_DumpGI_ui M       missing M       install-sh
Added -noclobber option to all *ui scripts to provide option to not overwrite
existing files.


git-svn-id: svn://141.35.69.214/CAT@255 85a05d3d-4204-4b9d-9be8-300d97d0f21f

diff --git a/Progs/CAT_DumpCurv_ui b/Progs/CAT_DumpCurv_ui
--- a/Progs/CAT_DumpCurv_ui
+++ b/Progs/CAT_DumpCurv_ui
@@ -16,6 +16,7 @@ use_absolute=0
 method=0
 fwhm=0
 removestr=''
+noclobber=0
 
 ########################################################
 # run main
@@ -37,18 +38,22 @@ DumpCurv ()
 {
   if [ -n "$ARGV_list" ]
   then
-	for i in $ARGV_list
-	do
-	   get_outputname $i
-	   echo calculating $outputname
-	   CAT_DumpCurv $i $outputname $method $fwhm $use_absolute
-	done
+  for i in $ARGV_list
+  do
+     get_outputname $i
+     if [ -f "${outputname}" ] && [ "$noclobber" == 1 ]; then
+        echo $outputname will be not overwritten. Do not use -noclobber if you want to overwrite file.
+     else
+       echo calculating $outputname
+       CAT_DumpCurv $i $outputname $method $fwhm $use_absolute
+     fi
+  done
   else
-	echo "No arguments given."
-	echo
-	usage
-	echo "Use the --help option for more information."
-	exit 1
+  echo "No arguments given."
+  echo
+  usage
+  echo "Use the --help option for more information."
+  exit 1
   fi
 
 }
@@ -105,47 +110,50 @@ parse_args ()
 
   while [ $# -gt 0 ]
   do
-	optname="`echo $1 | sed 's,=.*,,'`"
-	optarg="`echo $1 | sed 's,^[^=]*=,,'`"
-	case "$1" in
-		--a* | -a*)
-			use_absolute=1
-			;;
-		--r* | -r*)
-			exit_if_empty "$optname" "$optarg"
-			removestr=$optarg
-			;;
-		--f* | -f*)
-			optarg=`echo $optarg | sed 's,[^0-9],,g'`
-			exit_if_empty "$optname" "$optarg"
-			fwhm=$optarg
-			;;
-		--mc | -mc)
-			method=0
-			;;
-		--g* | -g*)
-			method=1
-			;;
-		--c* | -c*)
-			method=2
-			;;
-		--s* | -s*)
-			method=3
-			;;
-		--mc0 | -mc0)
-			method=4
-			;;
-		-h | --help | -v | --version | -V)
-			help
-			exit 1
-			;;
-		-*)
-			echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
-			;;
-		*)
-			ARGV_list="$ARGV_list $1"
-			;;
-	esac
+  optname="`echo $1 | sed 's,=.*,,'`"
+  optarg="`echo $1 | sed 's,^[^=]*=,,'`"
+  case "$1" in
+    --a* | -a*)
+      use_absolute=1
+      ;;
+    --r* | -r*)
+      exit_if_empty "$optname" "$optarg"
+      removestr=$optarg
+      ;;
+    --f* | -f*)
+      optarg=`echo $optarg | sed 's,[^0-9],,g'`
+      exit_if_empty "$optname" "$optarg"
+      fwhm=$optarg
+      ;;
+    --n* | -n*)
+      noclobber=1
+      ;;
+    --mc | -mc)
+      method=0
+      ;;
+    --g* | -g*)
+      method=1
+      ;;
+    --c* | -c*)
+      method=2
+      ;;
+    --s* | -s*)
+      method=3
+      ;;
+    --mc0 | -mc0)
+      method=4
+      ;;
+    -h | --help | -v | --version | -V)
+      help
+      exit 1
+      ;;
+    -*)
+      echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
+      ;;
+    *)
+      ARGV_list="$ARGV_list $1"
+      ;;
+  esac
     shift
   done
 
@@ -166,8 +174,8 @@ exit_if_empty ()
 
   if [ -z "$val" ]
   then
-	echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
-	exit 1
+  echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
+  exit 1
   fi
 }
 
@@ -177,9 +185,9 @@ exit_if_empty ()
 usage ()
 {
 cat <<__EOM__
-USAGE: CAT_DumpCurv_ui name [name2 name3 ... nameN]  [-mc|-mc0|-gc|-cv|-si] [-a]
+USAGE: CAT_DumpCurv_ui name [name2 name3 ... nameN] [-noclobber] [-mc|-mc0|-gc|-cv|-si] [-a]
         [-f=fwhm_in_mm] [-r=remove_str_from_outputname]
-		
+    
 __EOM__
 }
 
@@ -198,18 +206,19 @@ diffusion heat kernel and values can be saved as absolute values.
 
 USAGE:
     CAT_DumpCurv_ui name.obj [name2.obj ... nameN.obj] [-mc|-mc0|-gc|-cv|-si] [-a]
-        [-f=fwhm_in_mm] [-r=remove_str_from_outputname]
+        [-noclobber] [-f=fwhm_in_mm] [-r=remove_str_from_outputname]
     
 OPTIONS:
-	name.obj   - input obj-file(s)
-	-f         - diffusion heat kernel smoothing defined in fwhm in mm
-	-a         - calculate absolute values of parameters
-	-r         - remove string from outputname
-	-mc        - calculate mean curvature averaged over 3mm [default]                
-	-mc0       - calculate mean curvature                
-	-gc        - calculate gaussian curvature                
-	-cv        - calculate curvedness                
-	-si        - calculate shape index                
+  name.obj   - input obj-file(s)
+  -f         - diffusion heat kernel smoothing defined in fwhm in mm
+  -a         - calculate absolute values of parameters
+  -r         - remove string from outputname
+  -mc        - calculate mean curvature averaged over 3mm [default]                
+  -mc0       - calculate mean curvature                
+  -gc        - calculate gaussian curvature                
+  -cv        - calculate curvedness                
+  -si        - calculate shape index                
+  -noclobber - do not overwrite existing file
     
 EXAMPLE:
     CAT_DumpCurv_ui *.obj -mc -a -f=10 -r=cerebrum_a305_12p
diff --git a/Progs/CAT_DumpGI_ui b/Progs/CAT_DumpGI_ui
--- a/Progs/CAT_DumpGI_ui
+++ b/Progs/CAT_DumpGI_ui
@@ -16,6 +16,7 @@ fwhm=30
 fwhm_surf=100
 method=0
 removestr=''
+noclobber=0
 
 ########################################################
 # run main
@@ -37,18 +38,22 @@ DumpGI ()
 {
   if [ -n "$ARGV_list" ]
   then
-	for i in $ARGV_list
-	do
-	   get_outputname $i
-	   echo calculating $outputname
-	   CAT_DumpGI $i $outputname $fwhm $fwhm_surf $method
-	done
+  for i in $ARGV_list
+  do
+     get_outputname $i
+     if [ -f "${outputname}" ] && [ "$noclobber" == 1 ]; then
+       echo $outputname will be not overwritten. Do not use -noclobber if you want to overwrite file.
+     else
+       echo calculating $outputname
+       CAT_DumpGI $i $outputname $fwhm $fwhm_surf $method
+     fi
+  done
   else
-	echo "No arguments given."
-	echo
-	usage
-	echo "Use the --help option for more information."
-	exit 1
+  echo "No arguments given."
+  echo
+  usage
+  echo "Use the --help option for more information."
+  exit 1
   fi
 
 }
@@ -95,46 +100,49 @@ parse_args ()
 
   while [ $# -gt 0 ]
   do
-	optname="`echo $1 | sed 's,=.*,,'`"
-	optarg="`echo $1 | sed 's,^[^=]*=,,'`"
-	case "$1" in
-		--r* | -r*)
-			exit_if_empty "$optname" "$optarg"
-			removestr=$optarg
-			;;
-		--sf* | -sf*)
-			optarg=`echo $optarg | sed 's,[^0-9],,g'`
-			exit_if_empty "$optname" "$optarg"
-			fwhm_surf=$optarg
-			;;
-		--f* | -f*)
-			optarg=`echo $optarg | sed 's,[^0-9],,g'`
-			exit_if_empty "$optname" "$optarg"
-			fwhm=$optarg
-			;;
-		--mc | -mc)
-			method=0
-			;;
-		--cv* | -cv*)
-			method=2
-			;;
-		--si* | -si*)
-			method=3
-			;;
-		--mc0 | -mc0)
-			method=4
-			;;
-		-h | --help | -v | --version | -V)
-			help
-			exit 1
-			;;
-		-*)
-			echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
-			;;
-		*)
-			ARGV_list="$ARGV_list $1"
-			;;
-	esac
+  optname="`echo $1 | sed 's,=.*,,'`"
+  optarg="`echo $1 | sed 's,^[^=]*=,,'`"
+  case "$1" in
+    --r* | -r*)
+      exit_if_empty "$optname" "$optarg"
+      removestr=$optarg
+      ;;
+    --sf* | -sf*)
+      optarg=`echo $optarg | sed 's,[^0-9],,g'`
+      exit_if_empty "$optname" "$optarg"
+      fwhm_surf=$optarg
+      ;;
+    --f* | -f*)
+      optarg=`echo $optarg | sed 's,[^0-9],,g'`
+      exit_if_empty "$optname" "$optarg"
+      fwhm=$optarg
+      ;;
+    --n* | -n*)
+      noclobber=1
+      ;;
+    --mc | -mc)
+      method=0
+      ;;
+    --cv* | -cv*)
+      method=2
+      ;;
+    --si* | -si*)
+      method=3
+      ;;
+    --mc0 | -mc0)
+      method=4
+      ;;
+    -h | --help | -v | --version | -V)
+      help
+      exit 1
+      ;;
+    -*)
+      echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
+      ;;
+    *)
+      ARGV_list="$ARGV_list $1"
+      ;;
+  esac
     shift
   done
 
@@ -155,8 +163,8 @@ exit_if_empty ()
 
   if [ -z "$val" ]
   then
-	echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
-	exit 1
+  echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
+  exit 1
   fi
 }
 
@@ -166,9 +174,9 @@ exit_if_empty ()
 usage ()
 {
 cat <<__EOM__
-USAGE: DumpGI_ui name [name2 name3 ... nameN]  [-mc|-mc0|-cv|-si]
+USAGE: DumpGI_ui name [name2 name3 ... nameN] [-noclobber]  [-mc|-mc0|-cv|-si]
         [-f=fwhm_in_mm] [-sf=surf_fwhm_in_mm] [-r=remove_str_from_ouputname]
-		
+    
 __EOM__
 }
 
@@ -185,18 +193,19 @@ Calculate gyrification index (GI) using the ratio of local surface area and loca
 surface area. Local surface area can be approximated by use of different methods.
 
 USAGE:
-    CAT_DumpGI_ui name.obj [name2.obj ... nameN.obj] [-mc|-mc0|-cv|-si]
+    CAT_DumpGI_ui name.obj [name2.obj ... nameN.obj] [-noclobber] [-mc|-mc0|-cv|-si]
         [-f=fwhm_in_mm] [-sf=surf_fwhm_in_mm] [-r=remove_str_from_ouputname]
     
 OPTIONS:
-	name.obj   - input obj-file(s)
-	-f         - diffusion heat kernel smoothing defined in fwhm in mm
-	-sf        - diffusion heat kernel smoothing defined in fwhm in mm for surface inflating
-	-r         - remove string from outputname
-	-mc        - calculate mean curvature averaged over 3mm [default]                
-	-mc0       - calculate mean curvature                
-	-cv        - calculate curvedness                
-	-si        - calculate shape index                
+  name.obj   - input obj-file(s)
+  -f         - diffusion heat kernel smoothing defined in fwhm in mm
+  -sf        - diffusion heat kernel smoothing defined in fwhm in mm for surface inflating
+  -r         - remove string from outputname
+  -mc        - calculate mean curvature averaged over 3mm [default]                
+  -mc0       - calculate mean curvature                
+  -cv        - calculate curvedness                
+  -si        - calculate shape index                
+    -noclobber - do not overwrite existing file
     
 EXAMPLE:
     CAT_DumpGI_ui *.obj -mc -a -f=30 -r=cerebrum_a305_12p
diff --git a/Progs/CAT_FractalDimensionFS_ui b/Progs/CAT_FractalDimensionFS_ui
--- a/Progs/CAT_FractalDimensionFS_ui
+++ b/Progs/CAT_FractalDimensionFS_ui
@@ -14,6 +14,7 @@
 
 hemi="lh rh"
 ascii=0
+noclobber=0
 
 ########################################################
 # run main
@@ -21,7 +22,7 @@ ascii=0
 
 main ()
 {
-	check_tools
+  check_tools
   parse_args ${1+"$@"}
   process
 
@@ -37,35 +38,47 @@ process ()
 
   if [ -n "$ARGV_list" ]
   then
-		for subject in $ARGV_list
-		do
+    for subject in $ARGV_list
+    do
 
-		  surfdir=${subject}/surf
-		  if [ ! -d "$surfdir" ]; then
-	  		echo Directory $surfdir not found.
-	  		exit 1
-	  	fi
+      surfdir=${subject}/surf
+      if [ ! -d "$surfdir" ]; then
+        echo Directory $surfdir not found.
+        break
+      fi
 
       subject_name=`basename $subject`
-    	tmp_name=/tmp/$$_central
-    	
-    	for i in $hemi; do
-    	  CAT_AverageSurfaces -avg ${tmp_name}_${i} ${surfdir}/${i}.pial ${surfdir}/${i}.white >/dev/null 2>&1
+      tmp_name=/tmp/$$_central
+      
+      for i in $hemi; do
+        for name in ${surfdir}/${i}.pial ${surfdir}/${i}.white ${surfdir}/${i}.sphere; do
+          if [ ! -f "$name" ]; then
+            echo File $name not found.
+            break
+          fi
+        done
+        
         name=${surfdir}/${i}.fd
         if [ "$ascii" == 1 ]; then
           name=${name}.txt
         fi
-    	  echo save local FD in $name
-    	  CAT_FractalDimension -sphere ${surfdir}/${i}.sphere -nosmooth ${tmp_name}_${i} ${surfdir}/${i}.sphere $name
-   		done
- 	  	rm ${tmp_name}*
-  	done
+        
+        if [ -f "${name}" ] && [ "$noclobber" == 1 ]; then
+          echo $name will be not overwritten. Do not use -noclobber if you want to overwrite file.
+        else
+          echo save local FD in $name
+          CAT_AverageSurfaces -avg ${tmp_name}_${i} ${surfdir}/${i}.pial ${surfdir}/${i}.white >/dev/null 2>&1
+          CAT_FractalDimension -sphere ${surfdir}/${i}.sphere -nosmooth ${tmp_name}_${i} ${surfdir}/${i}.sphere $name
+          if [ -f ${tmp_name}_${i} ]; then rm ${tmp_name}_${i}; fi
+        fi
+      done
+    done
   else
-		echo "No arguments given."
-		echo
-		usage
-		echo "Use the --help option for more information."
-		exit 1
+    echo "No arguments given."
+    echo
+    usage
+    echo "Use the --help option for more information."
+    exit 1
   fi
 
 }
@@ -81,34 +94,37 @@ parse_args ()
 
   while [ $# -gt 0 ]
   do
-	optname="`echo $1 | sed 's,=.*,,'`"
-	optarg="`echo $1 | sed 's,^[^=]*=,,'`"
-	case "$1" in
-		--f* | -f*)
-			optarg=`echo $optarg | sed 's,[^0-9],,g'`
-			exit_if_empty "$optname" "$optarg"
-			fwhm=$optarg
-			;;
-		--a* | -a*)
-			ascii=1
-			;;
-		--lh* | -lh*)
-			hemi=lh
-			;;
-		--rh* | -rh*)
-			hemi=rh
-			;;
-		-h | --help | -v | --version | -V)
-			help
-			exit 1
-			;;
-		-*)
-			echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
-			;;
-		*)
-			ARGV_list="$ARGV_list $1"
-			;;
-	esac
+  optname="`echo $1 | sed 's,=.*,,'`"
+  optarg="`echo $1 | sed 's,^[^=]*=,,'`"
+  case "$1" in
+    --f* | -f*)
+      optarg=`echo $optarg | sed 's,[^0-9],,g'`
+      exit_if_empty "$optname" "$optarg"
+      fwhm=$optarg
+      ;;
+    --a* | -a*)
+      ascii=1
+      ;;
+    --n* | -n*)
+      noclobber=1
+      ;;
+    --lh* | -lh*)
+      hemi=lh
+      ;;
+    --rh* | -rh*)
+      hemi=rh
+      ;;
+    -h | --help | -v | --version | -V)
+      help
+      exit 1
+      ;;
+    -*)
+      echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
+      ;;
+    *)
+      ARGV_list="$ARGV_list $1"
+      ;;
+  esac
     shift
   done
 
@@ -129,8 +145,8 @@ exit_if_empty ()
 
   if [ -z "$val" ]
   then
-	echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
-	exit 1
+  echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
+  exit 1
   fi
 }
 
@@ -140,12 +156,12 @@ exit_if_empty ()
 
 check_tools ()
 {
-	for name in CAT_FractalDimension CAT_AverageSurfaces; do
-	  found=`which ${name}`
-  	if [ ! -n "$found" ];then
-    	echo $name not found.
-    	exit 1
-  	fi
+  for name in CAT_FractalDimension CAT_AverageSurfaces; do
+    found=`which ${name}`
+    if [ ! -n "$found" ];then
+      echo $name not found.
+      exit 1
+    fi
   done
 }
 
@@ -155,8 +171,8 @@ check_tools ()
 usage ()
 {
 cat <<__EOM__
-USAGE: CAT_FractalDimensionFS_ui subject [subject2 .. subjectN] [-a] [-lh|-rh]
-		
+USAGE: CAT_FractalDimensionFS_ui subject [subject2 .. subjectN] [-a] [-noclobber] [-lh|-rh]
+    
 __EOM__
 }
 
@@ -173,13 +189,14 @@ Calculate fractal dimension (FD) of central surface fo freesurfer surfaces. The 
 and resampled back to the original surface.
 
 USAGE:
-        CAT_FractalDimensionFS_ui subject [subject2 .. subjectN] [-a] [-lh|rh]                      
+        CAT_FractalDimensionFS_ui subject [subject2 .. subjectN] [-a] [-noclobber] [-lh|rh]                      
     
 OPTIONS:
-	subject    - one or more subject directories
-	-a         - save output as ascii (text) file
-	-lh        - resample left hemisphere only
-	-rh        - resample right hemisphere only
+  subject    - one or more subject directories
+  -a         - save output as ascii (text) file
+  -lh        - resample left hemisphere only
+  -rh        - resample right hemisphere only
+  -noclobber - do not overwrite existing file
     
 EXAMPLE:
     CAT_FractalDimensionFS_ui ${SUBJECTS_DIR}/[a-d]*
diff --git a/Progs/CAT_ResampleFS_ui b/Progs/CAT_ResampleFS_ui
--- a/Progs/CAT_ResampleFS_ui
+++ b/Progs/CAT_ResampleFS_ui
@@ -12,12 +12,13 @@
 # global parameters
 ########################################################
 
-fwhm=0
 measure=thickness
 output_dir="."
 reg=sphere.reg
 template=$FREESURFER_HOME/subjects/fsaverage
+fwhm=0
 ascii=0
+noclobber=0
 hemi="lh rh"
 
 ########################################################
@@ -26,7 +27,7 @@ hemi="lh rh"
 
 main ()
 {
-	check_tools
+  check_tools
   parse_args ${1+"$@"}
   preprocess
 
@@ -41,55 +42,65 @@ preprocess ()
 {
 
   if [ ! -d "$output_dir" ]; then
- 		echo Create directory ${output_dir}.
- 		mkdir -p $output_dir
- 	fi
+    echo Create directory ${output_dir}.
+    mkdir -p $output_dir
+  fi
   
   if [ -n "$ARGV_list" ]
   then
-		for subject in $ARGV_list
-		do
+    for subject in $ARGV_list
+    do
 
-		  surfdir=${subject}/surf
-		  if [ ! -d "$surfdir" ]; then
-	  		echo Directory $surfdir not found.
-	  		exit 1
-	  	fi
-
-		  targetdir=${template}/surf
-		  if [ ! -d "$targetdir" ]; then
-	  		echo Directory $targetdir not found.
-	  		exit 1
-	  	fi
+      surfdir=${subject}/surf
+      targetdir=${template}/surf
+      for name in $surfdir $targetdir; do
+        if [ ! -d "$name" ]; then
+          echo Directory $name not found.
+          break
+        fi
+      done
 
       subject_name=`basename $subject`
-    	tmp_name=/tmp/$$_resample
-    	for i in $hemi; do
+      tmp_name=/tmp/$$_resample
+      for i in $hemi; do
         if [ ! "$fwhm" == 0 ]; then
+        
           name=${output_dir}/${fwhm}mm.${measure}.${i}.resample.${subject_name}
           if [ "$ascii" == 1 ]; then
             name=${name}.txt
           fi
-	    	  CAT_ResampleSurf ${surfdir}/${i}.smoothwm ${surfdir}/${i}.${reg} ${targetdir}/${i}.sphere $tmp_name ${surfdir}/${i}.${measure} ${tmp_name}.txt
-	    	  CAT_BlurSurfHK $tmp_name $name $fwhm ${tmp_name}.txt
-	    	  echo resample and smooth to $name
+        
+          if [ -f "${name}" ] && [ "$noclobber" == 1 ]; then
+            echo $name will be not overwritten. Do not use -noclobber if you want to overwrite $name.
+          else
+            CAT_ResampleSurf ${surfdir}/${i}.smoothwm ${surfdir}/${i}.${reg} ${targetdir}/${i}.sphere $tmp_name ${surfdir}/${i}.${measure} ${tmp_name}.txt
+            CAT_BlurSurfHK $tmp_name $name $fwhm ${tmp_name}.txt
+            echo resample and smooth to $name          
+          fi
+        
         else
           name=${output_dir}/${measure}.${i}.resample.${subject}
           if [ "$ascii" == 1 ]; then
             name=${name}.txt
           fi
-	    	  CAT_ResampleSurf ${surfdir}/${i}.smoothwm ${surfdir}/${i}.${reg} ${targetdir}/${i}.sphere $tmp_name ${surfdir}/${i}.${measure} $name
-	    	  echo resample to $name
-  	  	fi
-  		done
- 	  	rm ${tmp_name}*
-  	done
+        
+          if [ -f "${name}" ] && [ "$noclobber" == 1 ]; then
+            echo $name will be not overwritten. Do not use -noclobber if you want to overwrite $name.
+          else
+            CAT_ResampleSurf ${surfdir}/${i}.smoothwm ${surfdir}/${i}.${reg} ${targetdir}/${i}.sphere $tmp_name ${surfdir}/${i}.${measure} $name
+            echo resample to $name
+          fi
+        
+        fi
+      done
+      rm ${tmp_name}*
+    done
   else
-		echo "No arguments given."
-		echo
-		usage
-		echo "Use the --help option for more information."
-		exit 1
+    echo "No arguments given."
+    echo
+    usage
+    echo "Use the --help option for more information."
+    exit 1
   fi
 
 }
@@ -105,50 +116,53 @@ parse_args ()
 
   while [ $# -gt 0 ]
   do
-	optname="`echo $1 | sed 's,=.*,,'`"
-	optarg="`echo $1 | sed 's,^[^=]*=,,'`"
-	case "$1" in
-		--f* | -f*)
-			optarg=`echo $optarg | sed 's,[^0-9],,g'`
-			exit_if_empty "$optname" "$optarg"
-			fwhm=$optarg
-			;;
-		--a* | -a*)
-			ascii=1
-			;;
-		--lh* | -lh*)
-			hemi=lh
-			;;
-		--rh* | -rh*)
-			hemi=rh
-			;;
-		--m* | -m*)
-			exit_if_empty "$optname" "$optarg"
-			measure=$optarg
-			;;
-		--t* | -t*)
-			exit_if_empty "$optname" "$optarg"
-			template=$optarg
-			;;
-		--o* | -o*)
-			exit_if_empty "$optname" "$optarg"
-			output_dir=$optarg
-			;;
-		--r* | -r*)
-			exit_if_empty "$optname" "$optarg"
-			reg=$optarg
-			;;
-		-h | --help | -v | --version | -V)
-			help
-			exit 1
-			;;
-		-*)
-			echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
-			;;
-		*)
-			ARGV_list="$ARGV_list $1"
-			;;
-	esac
+  optname="`echo $1 | sed 's,=.*,,'`"
+  optarg="`echo $1 | sed 's,^[^=]*=,,'`"
+  case "$1" in
+    --f* | -f*)
+      optarg=`echo $optarg | sed 's,[^0-9],,g'`
+      exit_if_empty "$optname" "$optarg"
+      fwhm=$optarg
+      ;;
+    --a* | -a*)
+      ascii=1
+      ;;
+    --n* | -n*)
+      noclobber=1
+      ;;
+    --lh* | -lh*)
+      hemi=lh
+      ;;
+    --rh* | -rh*)
+      hemi=rh
+      ;;
+    --m* | -m*)
+      exit_if_empty "$optname" "$optarg"
+      measure=$optarg
+      ;;
+    --t* | -t*)
+      exit_if_empty "$optname" "$optarg"
+      template=$optarg
+      ;;
+    --o* | -o*)
+      exit_if_empty "$optname" "$optarg"
+      output_dir=$optarg
+      ;;
+    --r* | -r*)
+      exit_if_empty "$optname" "$optarg"
+      reg=$optarg
+      ;;
+    -h | --help | -v | --version | -V)
+      help
+      exit 1
+      ;;
+    -*)
+      echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
+      ;;
+    *)
+      ARGV_list="$ARGV_list $1"
+      ;;
+  esac
     shift
   done
 
@@ -169,8 +183,8 @@ exit_if_empty ()
 
   if [ -z "$val" ]
   then
-	echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
-	exit 1
+  echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
+  exit 1
   fi
 }
 
@@ -180,12 +194,12 @@ exit_if_empty ()
 
 check_tools ()
 {
-	for name in CAT_ResampleSphericalSurf CAT_BlurSurfHK; do
-	  found=`which ${name}`
-  	if [ ! -n "$found" ];then
-    	echo $name not found.
-    	exit 1
-  	fi
+  for name in CAT_ResampleSphericalSurf CAT_BlurSurfHK; do
+    found=`which ${name}`
+    if [ ! -n "$found" ];then
+      echo $name not found.
+      exit 1
+    fi
   done
 }
 
@@ -197,7 +211,7 @@ usage ()
 cat <<__EOM__
 USAGE: CAT_ResampleFS_ui subject [subject2 .. subjectN] [-f=fwhm_in_mm] [-a] [-lh|-rh]
                           [-o=output_directory] [-m=measure] [-r=surfreg] [-t=target_surface]                      
-		
+    
 __EOM__
 }
 
@@ -214,19 +228,20 @@ Resample surface values to a parametric tetrahedral sphere. The resampled values
 optionally smoothed on the target surface using a diffusion heat kernel.
 
 USAGE:
-        CAT_ResampleFS_ui subject [subject2 .. subjectN] [-f=fwhm_in_mm] [-a] [-lh|-rh]
+        CAT_ResampleFS_ui subject [subject2 .. subjectN] [-f=fwhm_in_mm] [-a] [-noclobber] [-lh|-rh]
                           [-o=output_directory] [-m=measure] [-r=surfreg] [-t=target_surface]                      
     
 OPTIONS:
-	subject    - one or more subject directories
-	-f         - diffusion heat kernel smoothing defined in fwhm in mm [default $fwhm]
-	-t         - target surface for resampling [default $template]
-	-o         - output directory (created if neccessary) [default $output_dir]                
-	-m         - surface measure as input [default $measure]                 
-	-r         - sperical surface for resampling [default $reg]                 
-	-a         - save output as ascii (text) file
-	-lh        - resample left hemisphere only
-	-rh        - resample right hemisphere only
+  subject    - one or more subject directories
+  -f         - diffusion heat kernel smoothing defined in fwhm in mm [default $fwhm]
+  -t         - target surface for resampling [default $template]
+  -o         - output directory (created if neccessary) [default $output_dir]                
+  -m         - surface measure as input [default $measure]                 
+  -r         - sperical surface for resampling [default $reg]                 
+  -a         - save output as ascii (text) file
+  -lh        - resample left hemisphere only
+  -rh        - resample right hemisphere only
+  -noclobber - do not overwrite existing file
     
 EXAMPLE:
     CAT_ResampleFS_ui ${SUBJECTS_DIR}/[a-d]* -f=20 -t=fsaverage -o=~/data -m=thickness
